### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by ivancucer** [EcomGraduates/loom-downloader#7]
Hi @EcomGraduates 

1. installed via `npm i loom-dl`
```
added 32 packages in 3s

3 packages are looking for funding
  run `npm fund` for details
```
2. then this command to download `node loom-dl https://www.loom.com/share/00f316f743954f92b1e2ccf8fc741e3e`
```
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module '/Users/macbookpro/loom-dl'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.5.1
```
any ideas?

PS.
macOS 14.5
Node.js v22.5.1

**Comment by EcomGraduates** [comment]
Try installing globally looks like you installed into a project

**Comment by ivancucer** [comment]
Nope it was installed globally `/Users/macbookpro/node_modules/loom-dl`
But for some reason, the command skips the main folder which is `node_modules`

**Comment by EcomGraduates** [comment]
run this command 

```
loom-dl -u  https://www.loom.com/share/00f316f743954f92b1e2ccf8fc741e3e
```

**Comment by ivancucer** [comment]
ah the whole point is to add this flag to make it work :) I apologize, my bad.

**Comment by EcomGraduates** [comment]
not a problem at all! just updated the readme as the instructions were not very clear :)
